// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.Data;

#nullable disable

namespace StudentManagement.Migrations
{
    [DbContext(typeof(StudentManagementDbContext))]
    [Migration("20250417151416_Seeding Students")]
    partial class SeedingStudents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagement.Models.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("Zip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            City = "Hyderabad",
                            Country = "India",
                            State = "Telangana",
                            StudentId = -1,
                            Zip = 500072
                        },
                        new
                        {
                            Id = -2,
                            City = "Hyderabad",
                            Country = "India",
                            State = "Telangana",
                            StudentId = -2,
                            Zip = 500043
                        },
                        new
                        {
                            Id = -3,
                            City = "Hyderabad",
                            Country = "India",
                            State = "Telangana",
                            StudentId = -3,
                            Zip = 500043
                        });
                });

            modelBuilder.Entity("StudentManagement.Models.Domain.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "ComputerScience",
                            Specialisation = "cyberSecurity",
                            StudentId = -1
                        },
                        new
                        {
                            Id = -2,
                            Name = "ComputerScience",
                            Specialisation = "cyberSecurity",
                            StudentId = -2
                        },
                        new
                        {
                            Id = -3,
                            Name = "ComputerScience",
                            Specialisation = "cyberSecurity",
                            StudentId = -3
                        });
                });

            modelBuilder.Entity("StudentManagement.Models.Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Email = "21r21a6273@mlrinstitutions.ac.in",
                            Name = "Karthik Balabathula",
                            RollNo = "21r21a6273"
                        },
                        new
                        {
                            Id = -2,
                            Email = "21r21a62C0@mlrinstitutions.ac.in",
                            Name = "Vemula Abhiram",
                            RollNo = "21r21a62C0"
                        },
                        new
                        {
                            Id = -3,
                            Email = "21r21a62A9@mlrinstitutions.ac.in",
                            Name = "Dineah Palapothula",
                            RollNo = "21r21a62A9"
                        });
                });

            modelBuilder.Entity("StudentManagement.Models.Domain.Address", b =>
                {
                    b.HasOne("StudentManagement.Models.Domain.Student", "Student")
                        .WithOne("Address")
                        .HasForeignKey("StudentManagement.Models.Domain.Address", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagement.Models.Domain.Department", b =>
                {
                    b.HasOne("StudentManagement.Models.Domain.Student", "Student")
                        .WithOne("Department")
                        .HasForeignKey("StudentManagement.Models.Domain.Department", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagement.Models.Domain.Student", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Department")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
